#!/bin/bash
DOCKER_IMAGE='jess/awscli'
MOUNT_DIR=/root/.aws
SOURCE_DIR=${HOME}/.aws

. docker-machine-functions
setup_environment

docker run -i -t --rm=true -e AWS_SECRET_KEY=${AWS_SECRET_KEY} -e AWS_ACCESS_KEY=${AWS_ACCESS_KEY} -v $SOURCE_DIR:$MOUNT_DIR $DOCKER_IMAGE "$@"
