#!/bin/bash
DOCKER_IMAGE='jess/awscli'
MOUNT_DIR=/root/.aws
SOURCE_DIR=/Users/dbogen/.aws

function die () {
  echo "ERROR:  $1"
  exit 1
}

B2D_STATUS=`boot2docker status`
if [[ ! $B2D_STATUS == running ]];  then
  boot2docker start
  if [[ $? -ne 0 ]]; then
    die "Could not start boot2docker."
  fi
fi
if [[ ! $DOCKER_HOST =~ ^tcp.* ]]; then
    eval $(boot2docker shellinit 2> /dev/null )
    if [[ $? -ne 0 ]]; then
      die "Could not set boot2docker shell variables."
    fi
fi

docker run -i -t --rm=true -e AWS_SECRET_KEY=${AWS_SECRET_KEY} -e AWS_ACCESS_KEY=${AWS_ACCESS_KEY} -v $SOURCE_DIR:$MOUNT_DIR $DOCKER_IMAGE "$@"
