#!/bin/bash
DOCKER_IMAGE='convert:latest'
SRC_DIR=${HOME}/Downloads
MOUNT_DIR=/dl

if [ $# -ne 2 ]; then
    echo  "Usage:  $0 <file_to_convert> <file_to_create>"
    exit 2
fi

. docker-machine-functions
setup_environment

docker run --rm=true -v $SRC_DIR:$MOUNT_DIR $DOCKER_IMAGE \
  /usr/bin/convert \
  $MOUNT_DIR/$1 $MOUNT_DIR/$2
