#!/bin/bash
DOCKER_IMAGE='ubuntu:latest'
SOURCE_DIR=${HOME}/.gnupg
MOUNT_DIR=/root/.gnupg

. docker-machine-functions
setup_environment

docker run -i -t --rm=true -v $SOURCE_DIR:$MOUNT_DIR $DOCKER_IMAGE /usr/bin/gpg "$@"
